services:
  app:
    image: real-estate-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    command: ["./build/BackendApp"]
    stdin_open: true
    tty: true
